/* eslint-disable */

export const AllTypesProps: Record<string,any> = {
	Query:{
		users:{
			distinct_on:{
				type:"users_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"users_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"users_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		users_aggregate:{
			distinct_on:{
				type:"users_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"users_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"users_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		users_by_pk:{
			id:{
				type:"uuid",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		capsules:{
			find:{
				type:"CapsulesFind",
				array:false,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			sort:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		capsulesPast:{
			find:{
				type:"CapsulesFind",
				array:false,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			sort:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		capsulesUpcoming:{
			find:{
				type:"CapsulesFind",
				array:false,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			sort:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		capsule:{
			id:{
				type:"ID",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		cores:{
			find:{
				type:"CoresFind",
				array:false,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			sort:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		coresPast:{
			find:{
				type:"CoresFind",
				array:false,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			sort:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		coresUpcoming:{
			find:{
				type:"CoresFind",
				array:false,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			sort:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		core:{
			id:{
				type:"ID",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		dragons:{
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		dragon:{
			id:{
				type:"ID",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		histories:{
			find:{
				type:"HistoryFind",
				array:false,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			sort:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		historiesResult:{
			find:{
				type:"HistoryFind",
				array:false,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			sort:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		history:{
			id:{
				type:"ID",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		landpads:{
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		landpad:{
			id:{
				type:"ID",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		launches:{
			find:{
				type:"LaunchFind",
				array:false,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			sort:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		launchesPast:{
			find:{
				type:"LaunchFind",
				array:false,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			sort:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		launchesPastResult:{
			find:{
				type:"LaunchFind",
				array:false,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			sort:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		launchesUpcoming:{
			find:{
				type:"LaunchFind",
				array:false,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			sort:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		launch:{
			id:{
				type:"ID",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		launchLatest:{
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		launchNext:{
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		launchpads:{
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		launchpad:{
			id:{
				type:"ID",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		missions:{
			find:{
				type:"MissionsFind",
				array:false,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		missionsResult:{
			find:{
				type:"MissionsFind",
				array:false,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		mission:{
			id:{
				type:"ID",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		payloads:{
			find:{
				type:"PayloadsFind",
				array:false,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			sort:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		payload:{
			id:{
				type:"ID",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		rockets:{
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		rocketsResult:{
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		rocket:{
			id:{
				type:"ID",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		ships:{
			find:{
				type:"ShipsFind",
				array:false,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			sort:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		shipsResult:{
			find:{
				type:"ShipsFind",
				array:false,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			sort:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		ship:{
			id:{
				type:"ID",
				array:false,
				arrayRequired:false,
				required:true
			}
		}
	},
	users_select_column: "enum",
	users_order_by:{
		id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		rocket:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		timestamp:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		twitter:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	order_by: "enum",
	users_bool_exp:{
		_and:{
			type:"users_bool_exp",
			array:true,
			arrayRequired:false,
			required:false
		},
		_not:{
			type:"users_bool_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		_or:{
			type:"users_bool_exp",
			array:true,
			arrayRequired:false,
			required:false
		},
		id:{
			type:"uuid_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"String_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		rocket:{
			type:"String_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		timestamp:{
			type:"timestamptz_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		twitter:{
			type:"String_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	uuid_comparison_exp:{
		_eq:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:false
		},
		_gt:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:false
		},
		_gte:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:false
		},
		_in:{
			type:"uuid",
			array:true,
			arrayRequired:false,
			required:true
		},
		_is_null:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		},
		_lt:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:false
		},
		_lte:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:false
		},
		_neq:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:false
		},
		_nin:{
			type:"uuid",
			array:true,
			arrayRequired:false,
			required:true
		}
	},
	uuid: "String",
	String_comparison_exp:{
		_eq:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_gt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_gte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_ilike:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		_is_null:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		},
		_like:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_lt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_lte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_neq:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_nilike:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_nin:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		_nlike:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_nsimilar:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_similar:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	timestamptz_comparison_exp:{
		_eq:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		},
		_gt:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		},
		_gte:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		},
		_in:{
			type:"timestamptz",
			array:true,
			arrayRequired:false,
			required:true
		},
		_is_null:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		},
		_lt:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		},
		_lte:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		},
		_neq:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		},
		_nin:{
			type:"timestamptz",
			array:true,
			arrayRequired:false,
			required:true
		}
	},
	timestamptz: "String",
	users_aggregate_fields:{
		count:{
			columns:{
				type:"users_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			distinct:{
				type:"Boolean",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	CapsulesFind:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		landings:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		mission:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		original_launch:{
			type:"Date",
			array:false,
			arrayRequired:false,
			required:false
		},
		reuse_count:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		status:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		type:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	Date: "String",
	CoresFind:{
		asds_attempts:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		asds_landings:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		block:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		id:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		missions:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		original_launch:{
			type:"Date",
			array:false,
			arrayRequired:false,
			required:false
		},
		reuse_count:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		rtls_attempts:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		rtls_landings:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		status:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		water_landing:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	HistoryFind:{
		end:{
			type:"Date",
			array:false,
			arrayRequired:false,
			required:false
		},
		flight_number:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		start:{
			type:"Date",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	LaunchFind:{
		apoapsis_km:{
			type:"Float",
			array:false,
			arrayRequired:false,
			required:false
		},
		block:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		cap_serial:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		capsule_reuse:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		core_flight:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		core_reuse:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		core_serial:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		customer:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		eccentricity:{
			type:"Float",
			array:false,
			arrayRequired:false,
			required:false
		},
		end:{
			type:"Date",
			array:false,
			arrayRequired:false,
			required:false
		},
		epoch:{
			type:"Date",
			array:false,
			arrayRequired:false,
			required:false
		},
		fairings_recovered:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		fairings_recovery_attempt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		fairings_reuse:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		fairings_reused:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		fairings_ship:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		gridfins:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		inclination_deg:{
			type:"Float",
			array:false,
			arrayRequired:false,
			required:false
		},
		land_success:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		landing_intent:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		landing_type:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		landing_vehicle:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		launch_date_local:{
			type:"Date",
			array:false,
			arrayRequired:false,
			required:false
		},
		launch_date_utc:{
			type:"Date",
			array:false,
			arrayRequired:false,
			required:false
		},
		launch_success:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		launch_year:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		legs:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		lifespan_years:{
			type:"Float",
			array:false,
			arrayRequired:false,
			required:false
		},
		longitude:{
			type:"Float",
			array:false,
			arrayRequired:false,
			required:false
		},
		manufacturer:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		mean_motion:{
			type:"Float",
			array:false,
			arrayRequired:false,
			required:false
		},
		mission_id:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		mission_name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		nationality:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		norad_id:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		orbit:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		payload_id:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		payload_type:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		periapsis_km:{
			type:"Float",
			array:false,
			arrayRequired:false,
			required:false
		},
		period_min:{
			type:"Float",
			array:false,
			arrayRequired:false,
			required:false
		},
		raan:{
			type:"Float",
			array:false,
			arrayRequired:false,
			required:false
		},
		reference_system:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		regime:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		reused:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		rocket_id:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		rocket_name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		rocket_type:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		second_stage_block:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		semi_major_axis_km:{
			type:"Float",
			array:false,
			arrayRequired:false,
			required:false
		},
		ship:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		side_core1_reuse:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		side_core2_reuse:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		site_id:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		site_name_long:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		site_name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		start:{
			type:"Date",
			array:false,
			arrayRequired:false,
			required:false
		},
		tbd:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		tentative_max_precision:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		tentative:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	MissionsFind:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		manufacturer:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		payload_id:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	PayloadsFind:{
		apoapsis_km:{
			type:"Float",
			array:false,
			arrayRequired:false,
			required:false
		},
		customer:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		eccentricity:{
			type:"Float",
			array:false,
			arrayRequired:false,
			required:false
		},
		epoch:{
			type:"Date",
			array:false,
			arrayRequired:false,
			required:false
		},
		inclination_deg:{
			type:"Float",
			array:false,
			arrayRequired:false,
			required:false
		},
		lifespan_years:{
			type:"Float",
			array:false,
			arrayRequired:false,
			required:false
		},
		longitude:{
			type:"Float",
			array:false,
			arrayRequired:false,
			required:false
		},
		manufacturer:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		mean_motion:{
			type:"Float",
			array:false,
			arrayRequired:false,
			required:false
		},
		nationality:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		norad_id:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		orbit:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		payload_id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		payload_type:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		periapsis_km:{
			type:"Float",
			array:false,
			arrayRequired:false,
			required:false
		},
		period_min:{
			type:"Float",
			array:false,
			arrayRequired:false,
			required:false
		},
		raan:{
			type:"Float",
			array:false,
			arrayRequired:false,
			required:false
		},
		reference_system:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		regime:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		reused:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		},
		semi_major_axis_km:{
			type:"Float",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	ShipsFind:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		model:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		type:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		role:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		active:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		},
		imo:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		mmsi:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		abs:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		class:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		weight_lbs:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		weight_kg:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		year_built:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		home_port:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		status:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		speed_kn:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		course_deg:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		latitude:{
			type:"Float",
			array:false,
			arrayRequired:false,
			required:false
		},
		longitude:{
			type:"Float",
			array:false,
			arrayRequired:false,
			required:false
		},
		successful_landings:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		attempted_landings:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		mission:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	Mutation:{
		delete_users:{
			where:{
				type:"users_bool_exp",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		insert_users:{
			objects:{
				type:"users_insert_input",
				array:true,
				arrayRequired:true,
				required:true
			},
			on_conflict:{
				type:"users_on_conflict",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		update_users:{
			_set:{
				type:"users_set_input",
				array:false,
				arrayRequired:false,
				required:false
			},
			where:{
				type:"users_bool_exp",
				array:false,
				arrayRequired:false,
				required:true
			}
		}
	},
	users_insert_input:{
		id:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		rocket:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		timestamp:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		},
		twitter:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	users_on_conflict:{
		constraint:{
			type:"users_constraint",
			array:false,
			arrayRequired:false,
			required:true
		},
		update_columns:{
			type:"users_update_column",
			array:true,
			arrayRequired:true,
			required:true
		}
	},
	users_constraint: "enum",
	users_update_column: "enum",
	users_set_input:{
		id:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		rocket:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		timestamp:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		},
		twitter:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	Subscription:{
		users:{
			distinct_on:{
				type:"users_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"users_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"users_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		users_aggregate:{
			distinct_on:{
				type:"users_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"users_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"users_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		users_by_pk:{
			id:{
				type:"uuid",
				array:false,
				arrayRequired:false,
				required:true
			}
		}
	},
	conflict_action: "enum",
	users_aggregate_order_by:{
		count:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		max:{
			type:"users_max_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		min:{
			type:"users_min_order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	users_max_order_by:{
		name:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		rocket:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		timestamp:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		twitter:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	users_min_order_by:{
		name:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		rocket:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		timestamp:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		twitter:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	users_arr_rel_insert_input:{
		data:{
			type:"users_insert_input",
			array:true,
			arrayRequired:true,
			required:true
		},
		on_conflict:{
			type:"users_on_conflict",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	users_obj_rel_insert_input:{
		data:{
			type:"users_insert_input",
			array:false,
			arrayRequired:false,
			required:true
		},
		on_conflict:{
			type:"users_on_conflict",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	ObjectID: "String"
}

export const ReturnTypes: Record<string,any> = {
	Query:{
		users:"users",
		users_aggregate:"users_aggregate",
		users_by_pk:"users",
		capsules:"Capsule",
		capsulesPast:"Capsule",
		capsulesUpcoming:"Capsule",
		capsule:"Capsule",
		company:"Info",
		cores:"Core",
		coresPast:"Core",
		coresUpcoming:"Core",
		core:"Core",
		dragons:"Dragon",
		dragon:"Dragon",
		histories:"History",
		historiesResult:"HistoriesResult",
		history:"History",
		landpads:"Landpad",
		landpad:"Landpad",
		launches:"Launch",
		launchesPast:"Launch",
		launchesPastResult:"LaunchesPastResult",
		launchesUpcoming:"Launch",
		launch:"Launch",
		launchLatest:"Launch",
		launchNext:"Launch",
		launchpads:"Launchpad",
		launchpad:"Launchpad",
		missions:"Mission",
		missionsResult:"MissionResult",
		mission:"Mission",
		payloads:"Payload",
		payload:"Payload",
		roadster:"Roadster",
		rockets:"Rocket",
		rocketsResult:"RocketsResult",
		rocket:"Rocket",
		ships:"Ship",
		shipsResult:"ShipsResult",
		ship:"Ship"
	},
	users:{
		id:"uuid",
		name:"String",
		rocket:"String",
		timestamp:"timestamptz",
		twitter:"String"
	},
	users_aggregate:{
		aggregate:"users_aggregate_fields",
		nodes:"users"
	},
	users_aggregate_fields:{
		count:"Int",
		max:"users_max_fields",
		min:"users_min_fields"
	},
	users_max_fields:{
		name:"String",
		rocket:"String",
		timestamp:"timestamptz",
		twitter:"String"
	},
	users_min_fields:{
		name:"String",
		rocket:"String",
		timestamp:"timestamptz",
		twitter:"String"
	},
	Capsule:{
		id:"ID",
		landings:"Int",
		missions:"CapsuleMission",
		original_launch:"Date",
		reuse_count:"Int",
		status:"String",
		type:"String",
		dragon:"Dragon"
	},
	CapsuleMission:{
		flight:"Int",
		name:"String"
	},
	Dragon:{
		active:"Boolean",
		crew_capacity:"Int",
		description:"String",
		diameter:"Distance",
		dry_mass_kg:"Int",
		dry_mass_lb:"Int",
		first_flight:"String",
		heat_shield:"DragonHeatShield",
		height_w_trunk:"Distance",
		id:"ID",
		launch_payload_mass:"Mass",
		launch_payload_vol:"Volume",
		name:"String",
		orbit_duration_yr:"Int",
		pressurized_capsule:"DragonPressurizedCapsule",
		return_payload_mass:"Mass",
		return_payload_vol:"Volume",
		sidewall_angle_deg:"Float",
		thrusters:"DragonThrust",
		trunk:"DragonTrunk",
		type:"String",
		wikipedia:"String"
	},
	Distance:{
		feet:"Float",
		meters:"Float"
	},
	DragonHeatShield:{
		dev_partner:"String",
		material:"String",
		size_meters:"Float",
		temp_degrees:"Int"
	},
	Mass:{
		kg:"Int",
		lb:"Int"
	},
	Volume:{
		cubic_feet:"Int",
		cubic_meters:"Int"
	},
	DragonPressurizedCapsule:{
		payload_volume:"Volume"
	},
	DragonThrust:{
		amount:"Int",
		fuel_1:"String",
		fuel_2:"String",
		pods:"Int",
		thrust:"Force",
		type:"String"
	},
	Force:{
		kN:"Float",
		lbf:"Float"
	},
	DragonTrunk:{
		cargo:"DragonTrunkCargo",
		trunk_volume:"Volume"
	},
	DragonTrunkCargo:{
		solar_array:"Int",
		unpressurized_cargo:"Boolean"
	},
	Info:{
		ceo:"String",
		coo:"String",
		cto_propulsion:"String",
		cto:"String",
		employees:"Int",
		founded:"Int",
		founder:"String",
		headquarters:"Address",
		launch_sites:"Int",
		links:"InfoLinks",
		name:"String",
		summary:"String",
		test_sites:"Int",
		valuation:"Float",
		vehicles:"Int"
	},
	Address:{
		address:"String",
		city:"String",
		state:"String"
	},
	InfoLinks:{
		elon_twitter:"String",
		flickr:"String",
		twitter:"String",
		website:"String"
	},
	Core:{
		asds_attempts:"Int",
		asds_landings:"Int",
		block:"Int",
		id:"ID",
		missions:"CapsuleMission",
		original_launch:"Date",
		reuse_count:"Int",
		rtls_attempts:"Int",
		rtls_landings:"Int",
		status:"String",
		water_landing:"Boolean"
	},
	History:{
		details:"String",
		event_date_unix:"Date",
		event_date_utc:"Date",
		id:"ID",
		links:"Link",
		title:"String",
		flight:"Launch"
	},
	Link:{
		article:"String",
		reddit:"String",
		wikipedia:"String"
	},
	Launch:{
		details:"String",
		id:"ID",
		is_tentative:"Boolean",
		launch_date_local:"Date",
		launch_date_unix:"Date",
		launch_date_utc:"Date",
		launch_site:"LaunchSite",
		launch_success:"Boolean",
		launch_year:"String",
		links:"LaunchLinks",
		mission_id:"String",
		mission_name:"String",
		rocket:"LaunchRocket",
		static_fire_date_unix:"Date",
		static_fire_date_utc:"Date",
		telemetry:"LaunchTelemetry",
		tentative_max_precision:"String",
		upcoming:"Boolean",
		ships:"Ship"
	},
	LaunchSite:{
		site_id:"String",
		site_name_long:"String",
		site_name:"String"
	},
	LaunchLinks:{
		article_link:"String",
		flickr_images:"String",
		mission_patch_small:"String",
		mission_patch:"String",
		presskit:"String",
		reddit_campaign:"String",
		reddit_launch:"String",
		reddit_media:"String",
		reddit_recovery:"String",
		video_link:"String",
		wikipedia:"String"
	},
	LaunchRocket:{
		fairings:"LaunchRocketFairings",
		first_stage:"LaunchRocketFirstStage",
		rocket_name:"String",
		rocket_type:"String",
		rocket:"Rocket",
		second_stage:"LaunchRocketSecondStage"
	},
	LaunchRocketFairings:{
		recovered:"Boolean",
		recovery_attempt:"Boolean",
		reused:"Boolean",
		ship:"String"
	},
	LaunchRocketFirstStage:{
		cores:"LaunchRocketFirstStageCore"
	},
	LaunchRocketFirstStageCore:{
		block:"Int",
		core:"Core",
		flight:"Int",
		gridfins:"Boolean",
		land_success:"Boolean",
		landing_intent:"Boolean",
		landing_type:"String",
		landing_vehicle:"String",
		legs:"Boolean",
		reused:"Boolean"
	},
	Rocket:{
		active:"Boolean",
		boosters:"Int",
		company:"String",
		cost_per_launch:"Int",
		country:"String",
		description:"String",
		diameter:"Distance",
		engines:"RocketEngines",
		first_flight:"Date",
		first_stage:"RocketFirstStage",
		height:"Distance",
		id:"ID",
		landing_legs:"RocketLandingLegs",
		mass:"Mass",
		name:"String",
		payload_weights:"RocketPayloadWeight",
		second_stage:"RocketSecondStage",
		stages:"Int",
		success_rate_pct:"Int",
		type:"String",
		wikipedia:"String"
	},
	RocketEngines:{
		number:"Int",
		type:"String",
		version:"String",
		layout:"String",
		engine_loss_max:"String",
		propellant_1:"String",
		propellant_2:"String",
		thrust_sea_level:"Force",
		thrust_vacuum:"Force",
		thrust_to_weight:"Float"
	},
	RocketFirstStage:{
		burn_time_sec:"Int",
		engines:"Int",
		fuel_amount_tons:"Float",
		reusable:"Boolean",
		thrust_sea_level:"Force",
		thrust_vacuum:"Force"
	},
	RocketLandingLegs:{
		number:"Int",
		material:"String"
	},
	RocketPayloadWeight:{
		id:"String",
		kg:"Int",
		lb:"Int",
		name:"String"
	},
	RocketSecondStage:{
		burn_time_sec:"Int",
		engines:"Int",
		fuel_amount_tons:"Float",
		payloads:"RocketSecondStagePayloads",
		thrust:"Force"
	},
	RocketSecondStagePayloads:{
		option_1:"String",
		composite_fairing:"RocketSecondStagePayloadCompositeFairing"
	},
	RocketSecondStagePayloadCompositeFairing:{
		height:"Distance",
		diameter:"Distance"
	},
	LaunchRocketSecondStage:{
		block:"Int",
		payloads:"Payload"
	},
	Payload:{
		customers:"String",
		id:"ID",
		manufacturer:"String",
		nationality:"String",
		norad_id:"Int",
		orbit_params:"PayloadOrbitParams",
		orbit:"String",
		payload_mass_kg:"Float",
		payload_mass_lbs:"Float",
		payload_type:"String",
		reused:"Boolean"
	},
	PayloadOrbitParams:{
		apoapsis_km:"Float",
		arg_of_pericenter:"Float",
		eccentricity:"Float",
		epoch:"Date",
		inclination_deg:"Float",
		lifespan_years:"Float",
		longitude:"Float",
		mean_anomaly:"Float",
		mean_motion:"Float",
		periapsis_km:"Float",
		period_min:"Float",
		raan:"Float",
		reference_system:"String",
		regime:"String",
		semi_major_axis_km:"Float"
	},
	LaunchTelemetry:{
		flight_club:"String"
	},
	Ship:{
		abs:"Int",
		active:"Boolean",
		attempted_landings:"Int",
		class:"Int",
		course_deg:"Int",
		home_port:"String",
		id:"ID",
		image:"String",
		imo:"Int",
		missions:"ShipMission",
		mmsi:"Int",
		model:"String",
		name:"String",
		position:"ShipLocation",
		roles:"String",
		speed_kn:"Float",
		status:"String",
		successful_landings:"Int",
		type:"String",
		url:"String",
		weight_kg:"Int",
		weight_lbs:"Int",
		year_built:"Int"
	},
	ShipMission:{
		flight:"String",
		name:"String"
	},
	ShipLocation:{
		latitude:"Float",
		longitude:"Float"
	},
	HistoriesResult:{
		result:"Result",
		data:"History"
	},
	Result:{
		totalCount:"Int"
	},
	Landpad:{
		attempted_landings:"String",
		details:"String",
		full_name:"String",
		id:"ID",
		landing_type:"String",
		location:"Location",
		status:"String",
		successful_landings:"String",
		wikipedia:"String"
	},
	Location:{
		latitude:"Float",
		longitude:"Float",
		name:"String",
		region:"String"
	},
	LaunchesPastResult:{
		result:"Result",
		data:"Launch"
	},
	Launchpad:{
		attempted_launches:"Int",
		details:"String",
		id:"ID",
		location:"Location",
		name:"String",
		status:"String",
		successful_launches:"Int",
		vehicles_launched:"Rocket",
		wikipedia:"String"
	},
	Mission:{
		description:"String",
		id:"ID",
		manufacturers:"String",
		name:"String",
		twitter:"String",
		website:"String",
		wikipedia:"String",
		payloads:"Payload"
	},
	MissionResult:{
		result:"Result",
		data:"Mission"
	},
	Roadster:{
		apoapsis_au:"Float",
		details:"String",
		earth_distance_km:"Float",
		earth_distance_mi:"Float",
		eccentricity:"Float",
		epoch_jd:"Float",
		inclination:"Float",
		launch_date_unix:"Date",
		launch_date_utc:"Date",
		launch_mass_kg:"Int",
		launch_mass_lbs:"Int",
		longitude:"Float",
		mars_distance_km:"Float",
		mars_distance_mi:"Float",
		name:"String",
		norad_id:"Int",
		orbit_type:"Float",
		periapsis_arg:"Float",
		periapsis_au:"Float",
		period_days:"Float",
		semi_major_axis_au:"Float",
		speed_kph:"Float",
		speed_mph:"Float",
		wikipedia:"String"
	},
	RocketsResult:{
		result:"Result",
		data:"Rocket"
	},
	ShipsResult:{
		result:"Result",
		data:"Ship"
	},
	Mutation:{
		delete_users:"users_mutation_response",
		insert_users:"users_mutation_response",
		update_users:"users_mutation_response"
	},
	users_mutation_response:{
		affected_rows:"Int",
		returning:"users"
	},
	Subscription:{
		users:"users",
		users_aggregate:"users_aggregate",
		users_by_pk:"users"
	},
	CoreMission:{
		name:"String",
		flight:"Int"
	}
}